jwt:
  key: ""
  hour: 24
embedder:
  base_url: "https://api.siliconflow.cn/v1"
  model: "BAAI/bge-m3"
  api_key: ""
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: ""
  name: "llm"
qdrant:
  host: "localhost"
  port: 6334